@url = http://localhost:5168
@patientId = 00000000-0000-0000-0000-000000000000


// Patients API ================

###
GET {{url}}/patients

###
GET {{url}}/patients/{{patientId}}

###
POST {{url}}/patients
Content-Type: application/json

{
    "name" : "Reksio",
    "type" : "Dog",
    "breed" : "mixed",
    "gender" : "Male",
    "description" : "",
    "dateOfBirth": "2023-04-20"
}